version: '2.1'
services:
  config:
    build: config-service
    ports:
      - 8888:8888
    hostname: localhost

  registry:
    build: registry
    hostname: localhost
    ports:
    - 8761:8761

  report-service:
    build: report-service
    hostname: localhost
    ports:
    - 7000:7000

  client:
    build: client
    hostname: localhost
    ports:
      - 3000:3000
