version: '2.1'
services:
  config:
    image: pavelitel/config-service:v1
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    container_name: config

  registry:
    image: pavelitel/registry:v1
    restart: unless-stopped
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    container_name: registry

  report-service:
    image: pavelitel/report-service:v1
    restart: unless-stopped
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    container_name: report-service

  account-service:
    image: pavelitel/account-service:v1
    restart: unless-stopped
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    container_name: account-service


  auth-service:
    image: pavelitel/auth-service:v1
    restart: unless-stopped
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    container_name: auth-service

  gateway:
    image: pavelitel/gateway:v2
    restart: unless-stopped
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    container_name: gateway

  client:
    image: pavelitel/client
    restart: unless-stopped
    container_name: client