server:
  port: 8778
  servlet:
    context-path: /accounts

spring:
  datasource:
    url: "jdbc:mysql://mysql-srv84190.ht-systems.ru:3306/srv84190_react?serverTimezone=UTC"
    username: srv84190_paha
    password: grib1111
  jpa:
    hibernate:
      ddl-auto:  update

  security:
    oauth2:
      client:
        clientId: account-service
        clientSecret: secret
        accessTokenUri: http://auth-service:5000/auth/oauth/token
        grant-type: client_credentials
        scope: server