server:
  port: 5000
  servlet:
    context-path: /auth

spring:
  datasource:
    url: "jdbc:mysql://mysql-srv84190.ht-systems.ru:3306/srv84190_react?serverTimezone=UTC"
    username: srv84190_paha
    password: grib1111
  jpa:
    hibernate:
      ddl-auto:  update